/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author manduchi
 */
public class SIG_SNAPSHOTSetup extends DeviceSetup {

    /**
     * Creates new form SIG_SNAPSHOTSetup
     */
    public SIG_SNAPSHOTSetup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deviceButtons1 = new DeviceButtons();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        deviceField1 = new DeviceField();
        deviceField2 = new DeviceField();
        deviceField3 = new DeviceField();
        jPanel3 = new javax.swing.JPanel();
        deviceField4 = new DeviceField();
        deviceField5 = new DeviceField();
        deviceDispatch1 = new DeviceDispatch();
        jPanel4 = new javax.swing.JPanel();
        deviceField6 = new DeviceField();
        deviceField7 = new DeviceField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        deviceField8 = new DeviceField();
        deviceField9 = new DeviceField();
        deviceField10 = new DeviceField();
        deviceField56 = new DeviceField();
        jPanel6 = new javax.swing.JPanel();
        deviceField11 = new DeviceField();
        deviceField12 = new DeviceField();
        deviceField13 = new DeviceField();
        deviceField57 = new DeviceField();
        jPanel7 = new javax.swing.JPanel();
        deviceField14 = new DeviceField();
        deviceField15 = new DeviceField();
        deviceField16 = new DeviceField();
        deviceField58 = new DeviceField();
        jPanel8 = new javax.swing.JPanel();
        deviceField17 = new DeviceField();
        deviceField18 = new DeviceField();
        deviceField19 = new DeviceField();
        deviceField59 = new DeviceField();
        jPanel9 = new javax.swing.JPanel();
        deviceField20 = new DeviceField();
        deviceField21 = new DeviceField();
        deviceField22 = new DeviceField();
        deviceField60 = new DeviceField();
        jPanel10 = new javax.swing.JPanel();
        deviceField23 = new DeviceField();
        deviceField24 = new DeviceField();
        deviceField25 = new DeviceField();
        deviceField61 = new DeviceField();
        jPanel11 = new javax.swing.JPanel();
        deviceField26 = new DeviceField();
        deviceField27 = new DeviceField();
        deviceField28 = new DeviceField();
        deviceField62 = new DeviceField();
        jPanel12 = new javax.swing.JPanel();
        deviceField29 = new DeviceField();
        deviceField30 = new DeviceField();
        deviceField31 = new DeviceField();
        deviceField63 = new DeviceField();
        jPanel13 = new javax.swing.JPanel();
        deviceField32 = new DeviceField();
        deviceField33 = new DeviceField();
        deviceField34 = new DeviceField();
        deviceField64 = new DeviceField();
        jPanel14 = new javax.swing.JPanel();
        deviceField35 = new DeviceField();
        deviceField36 = new DeviceField();
        deviceField37 = new DeviceField();
        deviceField65 = new DeviceField();
        jPanel15 = new javax.swing.JPanel();
        deviceField38 = new DeviceField();
        deviceField39 = new DeviceField();
        deviceField40 = new DeviceField();
        deviceField66 = new DeviceField();
        jPanel16 = new javax.swing.JPanel();
        deviceField41 = new DeviceField();
        deviceField42 = new DeviceField();
        deviceField43 = new DeviceField();
        deviceField67 = new DeviceField();
        jPanel17 = new javax.swing.JPanel();
        deviceField44 = new DeviceField();
        deviceField45 = new DeviceField();
        deviceField46 = new DeviceField();
        deviceField68 = new DeviceField();
        jPanel18 = new javax.swing.JPanel();
        deviceField47 = new DeviceField();
        deviceField48 = new DeviceField();
        deviceField49 = new DeviceField();
        deviceField69 = new DeviceField();
        jPanel19 = new javax.swing.JPanel();
        deviceField50 = new DeviceField();
        deviceField51 = new DeviceField();
        deviceField52 = new DeviceField();
        deviceField70 = new DeviceField();
        jPanel20 = new javax.swing.JPanel();
        deviceField53 = new DeviceField();
        deviceField54 = new DeviceField();
        deviceField55 = new DeviceField();
        deviceField71 = new DeviceField();

        setDeviceProvider("spilds.rfx.local:8100");
        setDeviceTitle("Signal Snapshot");
        setDeviceType("SIG_SNAPSHOT");
        setHeight(350);
        setWidth(700);
        getContentPane().add(deviceButtons1, java.awt.BorderLayout.PAGE_END);

        jPanel1.setLayout(new java.awt.GridLayout(3, 1));

        deviceField1.setIdentifier("");
        deviceField1.setLabelString("DB Server: ");
        deviceField1.setNumCols(15);
        deviceField1.setOffsetNid(3);
        deviceField1.setTextOnly(true);
        jPanel2.add(deviceField1);

        deviceField2.setIdentifier("");
        deviceField2.setLabelString("User: ");
        deviceField2.setOffsetNid(4);
        deviceField2.setTextOnly(true);
        jPanel2.add(deviceField2);

        deviceField3.setIdentifier("");
        deviceField3.setLabelString("Passwd: ");
        deviceField3.setOffsetNid(5);
        deviceField3.setTextOnly(true);
        jPanel2.add(deviceField3);

        jPanel1.add(jPanel2);

        deviceField4.setIdentifier("");
        deviceField4.setLabelString("Database");
        deviceField4.setOffsetNid(2);
        deviceField4.setTextOnly(true);
        jPanel3.add(deviceField4);

        deviceField5.setIdentifier("");
        deviceField5.setLabelString("Table: ");
        deviceField5.setOffsetNid(6);
        deviceField5.setTextOnly(true);
        jPanel3.add(deviceField5);
        jPanel3.add(deviceDispatch1);

        jPanel1.add(jPanel3);

        deviceField6.setIdentifier("");
        deviceField6.setLabelString("Times: ");
        deviceField6.setNumCols(20);
        deviceField6.setOffsetNid(7);
        jPanel4.add(deviceField6);

        deviceField7.setIdentifier("");
        deviceField7.setLabelString("Num Signals: ");
        deviceField7.setOffsetNid(8);
        jPanel4.add(deviceField7);

        jPanel1.add(jPanel4);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        deviceField8.setIdentifier("");
        deviceField8.setLabelString("Column Name: ");
        deviceField8.setOffsetNid(11);
        deviceField8.setTextOnly(true);
        jPanel5.add(deviceField8);

        deviceField9.setIdentifier("");
        deviceField9.setLabelString("Rel.Start: ");
        deviceField9.setNumCols(8);
        deviceField9.setOffsetNid(14);
        jPanel5.add(deviceField9);

        deviceField10.setIdentifier("");
        deviceField10.setLabelString("Rel. End: ");
        deviceField10.setNumCols(8);
        deviceField10.setOffsetNid(15);
        jPanel5.add(deviceField10);

        deviceField56.setIdentifier("");
        deviceField56.setLabelString("Signal: ");
        deviceField56.setNumCols(40);
        deviceField56.setOffsetNid(16);
        jPanel5.add(deviceField56);

        jTabbedPane1.addTab("Sig1", jPanel5);

        deviceField11.setIdentifier("");
        deviceField11.setLabelString("Column Name: ");
        deviceField11.setOffsetNid(19);
        deviceField11.setTextOnly(true);
        jPanel6.add(deviceField11);

        deviceField12.setIdentifier("");
        deviceField12.setLabelString("Rel.Start: ");
        deviceField12.setNumCols(8);
        deviceField12.setOffsetNid(22);
        jPanel6.add(deviceField12);

        deviceField13.setIdentifier("");
        deviceField13.setLabelString("Rel. End: ");
        deviceField13.setNumCols(8);
        deviceField13.setOffsetNid(23);
        jPanel6.add(deviceField13);

        deviceField57.setIdentifier("");
        deviceField57.setLabelString("Signal: ");
        deviceField57.setNumCols(40);
        deviceField57.setOffsetNid(24);
        jPanel6.add(deviceField57);

        jTabbedPane1.addTab("Sig2", jPanel6);

        deviceField14.setIdentifier("");
        deviceField14.setLabelString("Column Name: ");
        deviceField14.setOffsetNid(27);
        deviceField14.setTextOnly(true);
        jPanel7.add(deviceField14);

        deviceField15.setIdentifier("");
        deviceField15.setLabelString("Rel.Start: ");
        deviceField15.setNumCols(8);
        deviceField15.setOffsetNid(30);
        jPanel7.add(deviceField15);

        deviceField16.setIdentifier("");
        deviceField16.setLabelString("Rel. End: ");
        deviceField16.setNumCols(8);
        deviceField16.setOffsetNid(31);
        jPanel7.add(deviceField16);

        deviceField58.setIdentifier("");
        deviceField58.setLabelString("Signal: ");
        deviceField58.setNumCols(40);
        deviceField58.setOffsetNid(32);
        jPanel7.add(deviceField58);

        jTabbedPane1.addTab("Sig3", jPanel7);

        deviceField17.setIdentifier("");
        deviceField17.setLabelString("Column Name: ");
        deviceField17.setOffsetNid(35);
        deviceField17.setTextOnly(true);
        jPanel8.add(deviceField17);

        deviceField18.setIdentifier("");
        deviceField18.setLabelString("Rel.Start: ");
        deviceField18.setNumCols(8);
        deviceField18.setOffsetNid(38);
        jPanel8.add(deviceField18);

        deviceField19.setIdentifier("");
        deviceField19.setLabelString("Rel. End: ");
        deviceField19.setNumCols(8);
        deviceField19.setOffsetNid(39);
        jPanel8.add(deviceField19);

        deviceField59.setIdentifier("");
        deviceField59.setLabelString("Signal: ");
        deviceField59.setNumCols(40);
        deviceField59.setOffsetNid(40);
        jPanel8.add(deviceField59);

        jTabbedPane1.addTab("Sig4", jPanel8);

        deviceField20.setIdentifier("");
        deviceField20.setLabelString("Column Name: ");
        deviceField20.setOffsetNid(43);
        deviceField20.setTextOnly(true);
        jPanel9.add(deviceField20);

        deviceField21.setIdentifier("");
        deviceField21.setLabelString("Rel.Start: ");
        deviceField21.setNumCols(8);
        deviceField21.setOffsetNid(46);
        jPanel9.add(deviceField21);

        deviceField22.setIdentifier("");
        deviceField22.setLabelString("Rel. End: ");
        deviceField22.setNumCols(8);
        deviceField22.setOffsetNid(47);
        jPanel9.add(deviceField22);

        deviceField60.setIdentifier("");
        deviceField60.setLabelString("Signal: ");
        deviceField60.setNumCols(40);
        deviceField60.setOffsetNid(48);
        jPanel9.add(deviceField60);

        jTabbedPane1.addTab("Sig5", jPanel9);

        deviceField23.setIdentifier("");
        deviceField23.setLabelString("Column Name: ");
        deviceField23.setOffsetNid(51);
        deviceField23.setTextOnly(true);
        jPanel10.add(deviceField23);

        deviceField24.setIdentifier("");
        deviceField24.setLabelString("Rel.Start: ");
        deviceField24.setNumCols(8);
        deviceField24.setOffsetNid(54);
        jPanel10.add(deviceField24);

        deviceField25.setIdentifier("");
        deviceField25.setLabelString("Rel. End: ");
        deviceField25.setNumCols(8);
        deviceField25.setOffsetNid(55);
        jPanel10.add(deviceField25);

        deviceField61.setIdentifier("");
        deviceField61.setLabelString("Signal: ");
        deviceField61.setNumCols(40);
        deviceField61.setOffsetNid(56);
        jPanel10.add(deviceField61);

        jTabbedPane1.addTab("Sig6", jPanel10);

        deviceField26.setIdentifier("");
        deviceField26.setLabelString("Column Name: ");
        deviceField26.setOffsetNid(59);
        deviceField26.setTextOnly(true);
        jPanel11.add(deviceField26);

        deviceField27.setIdentifier("");
        deviceField27.setLabelString("Rel.Start: ");
        deviceField27.setNumCols(8);
        deviceField27.setOffsetNid(62);
        jPanel11.add(deviceField27);

        deviceField28.setIdentifier("");
        deviceField28.setLabelString("Rel. End: ");
        deviceField28.setNumCols(8);
        deviceField28.setOffsetNid(63);
        jPanel11.add(deviceField28);

        deviceField62.setIdentifier("");
        deviceField62.setLabelString("Signal: ");
        deviceField62.setNumCols(40);
        deviceField62.setOffsetNid(64);
        jPanel11.add(deviceField62);

        jTabbedPane1.addTab("Sig7", jPanel11);

        deviceField29.setIdentifier("");
        deviceField29.setLabelString("Column Name: ");
        deviceField29.setOffsetNid(67);
        deviceField29.setTextOnly(true);
        jPanel12.add(deviceField29);

        deviceField30.setIdentifier("");
        deviceField30.setLabelString("Rel.Start: ");
        deviceField30.setNumCols(8);
        deviceField30.setOffsetNid(70);
        jPanel12.add(deviceField30);

        deviceField31.setIdentifier("");
        deviceField31.setLabelString("Rel. End: ");
        deviceField31.setNumCols(8);
        deviceField31.setOffsetNid(71);
        jPanel12.add(deviceField31);

        deviceField63.setIdentifier("");
        deviceField63.setLabelString("Signal: ");
        deviceField63.setNumCols(40);
        deviceField63.setOffsetNid(72);
        jPanel12.add(deviceField63);

        jTabbedPane1.addTab("Sig8", jPanel12);

        deviceField32.setIdentifier("");
        deviceField32.setLabelString("Column Name: ");
        deviceField32.setOffsetNid(75);
        deviceField32.setTextOnly(true);
        jPanel13.add(deviceField32);

        deviceField33.setIdentifier("");
        deviceField33.setLabelString("Rel.Start: ");
        deviceField33.setNumCols(8);
        deviceField33.setOffsetNid(78);
        jPanel13.add(deviceField33);

        deviceField34.setIdentifier("");
        deviceField34.setLabelString("Rel. End: ");
        deviceField34.setNumCols(8);
        deviceField34.setOffsetNid(79);
        jPanel13.add(deviceField34);

        deviceField64.setIdentifier("");
        deviceField64.setLabelString("Signal: ");
        deviceField64.setNumCols(40);
        deviceField64.setOffsetNid(80);
        jPanel13.add(deviceField64);

        jTabbedPane1.addTab("Sig9", jPanel13);

        deviceField35.setIdentifier("");
        deviceField35.setLabelString("Column Name: ");
        deviceField35.setOffsetNid(83);
        deviceField35.setTextOnly(true);
        jPanel14.add(deviceField35);

        deviceField36.setIdentifier("");
        deviceField36.setLabelString("Rel.Start: ");
        deviceField36.setNumCols(8);
        deviceField36.setOffsetNid(86);
        jPanel14.add(deviceField36);

        deviceField37.setIdentifier("");
        deviceField37.setLabelString("Rel. End: ");
        deviceField37.setNumCols(8);
        deviceField37.setOffsetNid(87);
        jPanel14.add(deviceField37);

        deviceField65.setIdentifier("");
        deviceField65.setLabelString("Signal: ");
        deviceField65.setNumCols(40);
        deviceField65.setOffsetNid(88);
        jPanel14.add(deviceField65);

        jTabbedPane1.addTab("Sig10", jPanel14);

        deviceField38.setIdentifier("");
        deviceField38.setLabelString("Column Name: ");
        deviceField38.setOffsetNid(91);
        deviceField38.setTextOnly(true);
        jPanel15.add(deviceField38);

        deviceField39.setIdentifier("");
        deviceField39.setLabelString("Rel.Start: ");
        deviceField39.setNumCols(8);
        deviceField39.setOffsetNid(94);
        jPanel15.add(deviceField39);

        deviceField40.setIdentifier("");
        deviceField40.setLabelString("Rel. End: ");
        deviceField40.setNumCols(8);
        deviceField40.setOffsetNid(95);
        jPanel15.add(deviceField40);

        deviceField66.setIdentifier("");
        deviceField66.setLabelString("Signal: ");
        deviceField66.setNumCols(40);
        deviceField66.setOffsetNid(96);
        jPanel15.add(deviceField66);

        jTabbedPane1.addTab("Sig11", jPanel15);

        deviceField41.setIdentifier("");
        deviceField41.setLabelString("Column Name: ");
        deviceField41.setOffsetNid(99);
        deviceField41.setTextOnly(true);
        jPanel16.add(deviceField41);

        deviceField42.setIdentifier("");
        deviceField42.setLabelString("Rel.Start: ");
        deviceField42.setNumCols(8);
        deviceField42.setOffsetNid(102);
        jPanel16.add(deviceField42);

        deviceField43.setIdentifier("");
        deviceField43.setLabelString("Rel. End: ");
        deviceField43.setNumCols(8);
        deviceField43.setOffsetNid(103);
        jPanel16.add(deviceField43);

        deviceField67.setIdentifier("");
        deviceField67.setLabelString("Signal: ");
        deviceField67.setNumCols(40);
        deviceField67.setOffsetNid(104);
        jPanel16.add(deviceField67);

        jTabbedPane1.addTab("Sig12", jPanel16);

        deviceField44.setIdentifier("");
        deviceField44.setLabelString("Column Name: ");
        deviceField44.setOffsetNid(107);
        deviceField44.setTextOnly(true);
        jPanel17.add(deviceField44);

        deviceField45.setIdentifier("");
        deviceField45.setLabelString("Rel.Start: ");
        deviceField45.setNumCols(8);
        deviceField45.setOffsetNid(110);
        jPanel17.add(deviceField45);

        deviceField46.setIdentifier("");
        deviceField46.setLabelString("Rel. End: ");
        deviceField46.setNumCols(8);
        deviceField46.setOffsetNid(111);
        jPanel17.add(deviceField46);

        deviceField68.setIdentifier("");
        deviceField68.setLabelString("Signal: ");
        deviceField68.setNumCols(40);
        deviceField68.setOffsetNid(112);
        jPanel17.add(deviceField68);

        jTabbedPane1.addTab("Sig13", jPanel17);

        deviceField47.setIdentifier("");
        deviceField47.setLabelString("Column Name: ");
        deviceField47.setOffsetNid(115);
        deviceField47.setTextOnly(true);
        jPanel18.add(deviceField47);

        deviceField48.setIdentifier("");
        deviceField48.setLabelString("Rel.Start: ");
        deviceField48.setNumCols(8);
        deviceField48.setOffsetNid(118);
        jPanel18.add(deviceField48);

        deviceField49.setIdentifier("");
        deviceField49.setLabelString("Rel. End: ");
        deviceField49.setNumCols(8);
        deviceField49.setOffsetNid(119);
        jPanel18.add(deviceField49);

        deviceField69.setIdentifier("");
        deviceField69.setLabelString("Signal: ");
        deviceField69.setNumCols(40);
        deviceField69.setOffsetNid(120);
        jPanel18.add(deviceField69);

        jTabbedPane1.addTab("Sig14", jPanel18);

        deviceField50.setIdentifier("");
        deviceField50.setLabelString("Column Name: ");
        deviceField50.setOffsetNid(123);
        deviceField50.setTextOnly(true);
        jPanel19.add(deviceField50);

        deviceField51.setIdentifier("");
        deviceField51.setLabelString("Rel.Start: ");
        deviceField51.setNumCols(8);
        deviceField51.setOffsetNid(126);
        jPanel19.add(deviceField51);

        deviceField52.setIdentifier("");
        deviceField52.setLabelString("Rel. End: ");
        deviceField52.setNumCols(8);
        deviceField52.setOffsetNid(127);
        jPanel19.add(deviceField52);

        deviceField70.setIdentifier("");
        deviceField70.setLabelString("Signal: ");
        deviceField70.setNumCols(40);
        deviceField70.setOffsetNid(128);
        jPanel19.add(deviceField70);

        jTabbedPane1.addTab("Sig15", jPanel19);

        deviceField53.setIdentifier("");
        deviceField53.setLabelString("Column Name: ");
        deviceField53.setOffsetNid(131);
        deviceField53.setTextOnly(true);
        jPanel20.add(deviceField53);

        deviceField54.setIdentifier("");
        deviceField54.setLabelString("Rel.Start: ");
        deviceField54.setNumCols(8);
        deviceField54.setOffsetNid(134);
        jPanel20.add(deviceField54);

        deviceField55.setIdentifier("");
        deviceField55.setLabelString("Rel. End: ");
        deviceField55.setNumCols(8);
        deviceField55.setOffsetNid(135);
        jPanel20.add(deviceField55);

        deviceField71.setIdentifier("");
        deviceField71.setLabelString("Signal: ");
        deviceField71.setNumCols(40);
        deviceField71.setOffsetNid(136);
        jPanel20.add(deviceField71);

        jTabbedPane1.addTab("Sig16", jPanel20);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        getAccessibleContext().setAccessibleName("");
        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private DeviceButtons deviceButtons1;
    private DeviceDispatch deviceDispatch1;
    private DeviceField deviceField1;
    private DeviceField deviceField10;
    private DeviceField deviceField11;
    private DeviceField deviceField12;
    private DeviceField deviceField13;
    private DeviceField deviceField14;
    private DeviceField deviceField15;
    private DeviceField deviceField16;
    private DeviceField deviceField17;
    private DeviceField deviceField18;
    private DeviceField deviceField19;
    private DeviceField deviceField2;
    private DeviceField deviceField20;
    private DeviceField deviceField21;
    private DeviceField deviceField22;
    private DeviceField deviceField23;
    private DeviceField deviceField24;
    private DeviceField deviceField25;
    private DeviceField deviceField26;
    private DeviceField deviceField27;
    private DeviceField deviceField28;
    private DeviceField deviceField29;
    private DeviceField deviceField3;
    private DeviceField deviceField30;
    private DeviceField deviceField31;
    private DeviceField deviceField32;
    private DeviceField deviceField33;
    private DeviceField deviceField34;
    private DeviceField deviceField35;
    private DeviceField deviceField36;
    private DeviceField deviceField37;
    private DeviceField deviceField38;
    private DeviceField deviceField39;
    private DeviceField deviceField4;
    private DeviceField deviceField40;
    private DeviceField deviceField41;
    private DeviceField deviceField42;
    private DeviceField deviceField43;
    private DeviceField deviceField44;
    private DeviceField deviceField45;
    private DeviceField deviceField46;
    private DeviceField deviceField47;
    private DeviceField deviceField48;
    private DeviceField deviceField49;
    private DeviceField deviceField5;
    private DeviceField deviceField50;
    private DeviceField deviceField51;
    private DeviceField deviceField52;
    private DeviceField deviceField53;
    private DeviceField deviceField54;
    private DeviceField deviceField55;
    private DeviceField deviceField56;
    private DeviceField deviceField57;
    private DeviceField deviceField58;
    private DeviceField deviceField59;
    private DeviceField deviceField6;
    private DeviceField deviceField60;
    private DeviceField deviceField61;
    private DeviceField deviceField62;
    private DeviceField deviceField63;
    private DeviceField deviceField64;
    private DeviceField deviceField65;
    private DeviceField deviceField66;
    private DeviceField deviceField67;
    private DeviceField deviceField68;
    private DeviceField deviceField69;
    private DeviceField deviceField7;
    private DeviceField deviceField70;
    private DeviceField deviceField71;
    private DeviceField deviceField8;
    private DeviceField deviceField9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
